import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import TopBar from '@/client-components/layout/top-bar';
import SideNavbar from '@/client-components/layout/side-navbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="grid h-screen grid-rows-[80px_1fr]">
          <TopBar />
          <div className="grid grid-cols-[auto_1fr] duration-50000 transition-all">
            <SideNavbar />
            <div className='px-4 py-2 md:px-7 md:py-4 max-h-[calc(100vh-80px)]'>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
